//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _39WCFClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHelloService")]
    public interface IHelloService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/Hello", ReplyAction="http://tempuri.org/IHelloService/HelloResponse")]
        string Hello(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/Hello", ReplyAction="http://tempuri.org/IHelloService/HelloResponse")]
        System.Threading.Tasks.Task<string> HelloAsync(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/GetMembers", ReplyAction="http://tempuri.org/IHelloService/GetMembersResponse")]
        System.Data.DataSet GetMembers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/GetMembers", ReplyAction="http://tempuri.org/IHelloService/GetMembersResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMembersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloServiceChannel : _39WCFClient.ServiceReference1.IHelloService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloServiceClient : System.ServiceModel.ClientBase<_39WCFClient.ServiceReference1.IHelloService>, _39WCFClient.ServiceReference1.IHelloService {
        
        public HelloServiceClient() {
        }
        
        public HelloServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Hello(string s) {
            return base.Channel.Hello(s);
        }
        
        public System.Threading.Tasks.Task<string> HelloAsync(string s) {
            return base.Channel.HelloAsync(s);
        }
        
        public System.Data.DataSet GetMembers() {
            return base.Channel.GetMembers();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMembersAsync() {
            return base.Channel.GetMembersAsync();
        }
    }
}
